global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Video Converter Service metrics
  - job_name: 'video-converter'
    static_configs:
      - targets: ['video-converter:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']